name: Build RustDesk for Windows

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Build RustDesk
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Create portable package
      run: |
        # Создаем папку для пакета
        mkdir rustdesk-portable
        # Копируем exe файл
        copy target\x86_64-pc-windows-msvc\release\rustdesk.exe rustdesk-portable\
        # Создаем конфиг
        mkdir rustdesk-portable\config
        echo [options] > rustdesk-portable\config\RustDesk2.toml
        echo relay-server = "vpnholod2.softether.net:21117" >> rustdesk-portable\config\RustDesk2.toml
        echo id-server = "vpnholod2.softether.net:21116" >> rustdesk-portable\config\RustDesk2.toml
        # Создаем BAT файл
        echo @echo off > rustdesk-portable\start.bat
        echo rustdesk.exe --id-server vpnholod2.softether.net:21116 --relay-server vpnholod2.softether.net:21117 >> rustdesk-portable\start.bat
        echo pause >> rustdesk-portable\start.bat
        # Архивируем
        7z a -r rustdesk-windows.zip rustdesk-portable\

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-windows
        path: rustdesk-windows.zip
