name: Build RustDesk Client (Advanced)

on:
  push:
    tags: ['v*.*.*']
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: rustdesk-windows
            asset_name: RustDesk-Windows.zip
            
          - os: ubuntu-latest  
            target: x86_64-unknown-linux-gnu
            artifact_name: rustdesk-linux
            asset_name: RustDesk-Linux.tar.gz
            
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: rustdesk-macos
            asset_name: RustDesk-macOS.tar.gz

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install system dependencies
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev libxdo-dev libxrandr-dev libxi-dev \
            libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev \
            libxkbcommon-dev libssl-dev pkg-config cmake ninja-build
        elif [ "${{ matrix.os }}" = "windows-latest" ]; then
          echo "VS Build Tools установлены автоматически"
        fi

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        components: rust-src

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: './ -> target'

    - name: Build application
      run: cargo build --release --target ${{ matrix.target }} --verbose

    - name: Run tests
      run: cargo test --release --target ${{ matrix.target }} --verbose

    - name: Optimize binary size
      run: |
        if [ "${{ matrix.os }}" != "windows-latest" ]; then
          strip target/${{ matrix.target }}/release/rustdesk
        fi

    - name: Configure for custom server
      run: |
        # Создаем конфиг файлы для каждого типа ОС
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          echo "Creating Windows config..."
          mkdir -p "target/${{ matrix.target }}/release/config/RustDesk"
          cat > "target/${{ matrix.target }}/release/config/RustDesk/RustDesk2.toml" << 'EOF'
[options]
relay-server = "vpnholod2.softether.net:21117"
api-server = "https://vpnholod2.softether.net:21117"
id-server = "vpnholod2.softether.net:21116"
key = ""
EOF
        elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          echo "Creating Linux config..."
          mkdir -p "target/${{ matrix.target }}/release/config/.config/RustDesk"
          cat > "target/${{ matrix.target }}/release/config/.config/RustDesk/RustDesk2.toml" << 'EOF'
[options]
relay-server = "vpnholod2.softether.net:21117"
api-server = "https://vpnholod2.softether.net:21117"
id-server = "vpnholod2.softether.net:21116"
key = "3hhFAlNgteYx8cz6k34lXI47jCrz2DSuZ7DcEPD835Q="
EOF
        else
          echo "Creating macOS config..."
          mkdir -p "target/${{ matrix.target }}/release/config/.config/RustDesk"
          cat > "target/${{ matrix.target }}/release/config/.config/RustDesk/RustDesk2.toml" << 'EOF'
[options]
relay-server = "vpnholod2.softether.net:21117"
api-server = "https://vpnholod2.softether.net:21117"
id-server = "vpnholod2.softether.net:21116"
key = "3hhFAlNgteYx8cz6k34lXI47jCrz2DSuZ7DcEPD835Q="
EOF
        fi

    - name: Package binary with config
      run: |
        mkdir -p release-package
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          # Копируем бинарник и конфиг
          cp target/${{ matrix.target }}/release/rustdesk.exe release-package/
          cp -r target/${{ matrix.target }}/release/config release-package/
          # Создаем BAT файл для запуска
          cat > release-package/start.bat << 'EOF'
@echo off
chcp 65001 > nul
echo Starting RustDesk with custom server...
rustdesk.exe --id-server vpnholod2.softether.net:21116 --relay-server vpnholod2.softether.net:21117
pause
EOF
          cd release-package && zip -r ../${{ matrix.asset_name }} ./*
        else
          # Копируем бинарник и конфиг
          cp target/${{ matrix.target }}/release/rustdesk release-package/
          cp -r target/${{ matrix.target }}/release/config release-package/
          # Создаем скрипт для запуска
          cat > release-package/start.sh << 'EOF'
#!/bin/bash
echo "Starting RustDesk with custom server..."
./rustdesk --id-server vpnholod2.softether.net:21116 --relay-server vpnholod2.softether.net:21117
EOF
          chmod +x release-package/start.sh
          cd release-package && tar -czf ../${{ matrix.asset_name }} ./*
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}-${{ github.sha }}
        path: ${{ matrix.asset_name }}
        retention-days: 90

    - name: Upload to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.asset_name }}
        draft: false
        prerelease: false

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify build status
        run: |
          echo "Build completed with status: ${{ needs.build.result }}"
